CREATE TABLE WALLET_USER(
	USER_ID INT(6) NOT NULL AUTO_INCREMENT,
	EMAIL_ID VARCHAR(255) UNIQUE NOT NULL,
	MOBILE_NUMBER VARCHAR(10) UNIQUE NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL, 
	MODIFIED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	constraint USER_ID_PK primary key (USER_ID)
);

CREATE TABLE PAYMENT_TYPE(
	PAYMENT_TYPE_ID INT(3),
	PAYMENT_FROM CHAR(1) NOT NULL,
	PAYMENT_TO CHAR(1) NOT NULL,
	PAYMENT_TYPE CHAR(1) NOT NULL,
	constraint PAYMENT_TYPE_ID_PK primary key (PAYMENT_TYPE_ID)
);

CREATE TABLE USER_TRANSACTION(
	USER_TRANSACTION_ID BIGINT(10) AUTO_INCREMENT,
	AMOUNT FLOAT(12) NOT NULL,
	TRANSACTION_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL, 
	PAYMENT_TYPE_ID INT(3) NOT NULL,
	REMARKS VARCHAR(50),
	INFO VARCHAR(100) NOT NULL,
	TRANSACTION_STATUS VARCHAR(10) NOT NULL,
	USER_ID INT(6),
	constraint USER_TRANSACTION_ID_PK primary key (USER_TRANSACTION_ID)
);

CREATE TABLE USER_TRANSACTION_MAPPING(
	USER_TRANSACTION_ID BIGINT(10) NOT NULL,
	USER_ID INT(6) NOT NULL,
	constraint TRANSACTION_USER_ID_UNQ UNIQUE (USER_TRANSACTION_ID, USER_ID)
);

ALTER TABLE PAYMENT_TYPE ADD CONSTRAINT PAYMENT_TYPE_FROM_CHK CHECK (PAYMENT_FROM IN ('B','W'));
ALTER TABLE PAYMENT_TYPE ADD CONSTRAINT PAYMENT_TYPE_TO_CHK CHECK (PAYMENT_TO IN ('B','W'));
ALTER TABLE PAYMENT_TYPE ADD CONSTRAINT PAYMENT_TYPE_CHK CHECK (PAYMENT_TYPE IN ('D','C'));

ALTER TABLE USER_TRANSACTION ADD CONSTRAINT USER_TXN_AMOUNT_CHK CHECK (AMOUNT > 0);
ALTER TABLE USER_TRANSACTION ADD CONSTRAINT USER_TXN_PAYMENT_TYPE_ID_FK FOREIGN KEY ( PAYMENT_TYPE_ID ) REFERENCES PAYMENT_TYPE( PAYMENT_TYPE_ID );
ALTER TABLE USER_TRANSACTION ADD CONSTRAINT USER_TXN_USER_ID_FK FOREIGN KEY ( USER_ID ) REFERENCES WALLET_USER( USER_ID );

ALTER TABLE USER_TRANSACTION ADD CONSTRAINT USER_TXN_STATUS_CHK CHECK (TRANSACTION_STATUS IN ('SUCCESS','FAILURE', 'PENDING'));

ALTER TABLE USER_TRANSACTION_MAPPING ADD CONSTRAINT USER_TXN_MPNG_USER_ID_FK FOREIGN KEY ( USER_ID ) REFERENCES WALLET_USER( USER_ID );
ALTER TABLE USER_TRANSACTION_MAPPING ADD CONSTRAINT USER_TXN_MPNG_TXN_ID_FK FOREIGN KEY ( USER_TRANSACTION_ID ) REFERENCES USER_TRANSACTION( USER_TRANSACTION_ID );



INSERT INTO WALLET_USER(USER_ID, EMAIL_ID, MOBILE_NUMBER, NAME, PASSWORD, CREATED_TIMESTAMP) VALUES(12121, 'bhanu@gmail.com', '9711236040', 'Bhanu Jain', '5ca462b3cabd2b7e735cecc7ad67c163bdf1edf26aa904ad241fea980b4f7379', SYSDATE()-INTERVAL 3106 DAY);
INSERT INTO WALLET_USER(USER_ID, EMAIL_ID, MOBILE_NUMBER, NAME, PASSWORD, CREATED_TIMESTAMP) VALUES(12122, 'b@gmail.com', '9701236040', 'Bhanu Jain', '5ca462b3cabd2b7e735cecc7ad67c163bdf1edf26aa904ad241fea980b4f7379', SYSDATE()-INTERVAL 3106 DAY);


INSERT INTO PAYMENT_TYPE(PAYMENT_TYPE_ID, PAYMENT_FROM, PAYMENT_TO, PAYMENT_TYPE) values (1,'W','W','C');
INSERT INTO PAYMENT_TYPE(PAYMENT_TYPE_ID, PAYMENT_FROM, PAYMENT_TO, PAYMENT_TYPE) values (2,'W','W','D');
INSERT INTO PAYMENT_TYPE(PAYMENT_TYPE_ID, PAYMENT_FROM, PAYMENT_TO, PAYMENT_TYPE) values (3,'B','W','C');

INSERT INTO USER_TRANSACTION(USER_TRANSACTION_ID,AMOUNT,TRANSACTION_TIMESTAMP,PAYMENT_TYPE_ID,REMARKS,INFO,TRANSACTION_STATUS, USER_ID) VALUES(1212003, 257.24, SYSDATE()-INTERVAL 1659 DAY, 3, '', 'money credited from bank to wallet', 'SUCCESS', 12121);
INSERT INTO USER_TRANSACTION(USER_TRANSACTION_ID,AMOUNT,TRANSACTION_TIMESTAMP,PAYMENT_TYPE_ID,REMARKS,INFO,TRANSACTION_STATUS, USER_ID) VALUES(1212004, 821.59, SYSDATE()-INTERVAL 1654 DAY, 3, '', 'money credited from bank to wallet', 'SUCCESS', 12121);

INSERT INTO USER_TRANSACTION_MAPPING(USER_TRANSACTION_ID,USER_ID) VALUES(1212003,12121);
INSERT INTO USER_TRANSACTION_MAPPING(USER_TRANSACTION_ID,USER_ID) VALUES(1212004,12121);


	
commit;